[toolchain]

[features]
resolution = true
skip-lint = false

[workspace]
members = ["."]

[programs.localnet]
arbitrage_contract = "7R2DEVjE6DQPsQYnLSaFwPQjp1RN5vR8BAfxNhociMxV"

[programs.devnet]
arbitrage_contract = "4ZqQT3aUpSMiAjmyaYj6yHjfJQH6k7v3XBSpgAhWU8uC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/zhengwei/Desktop/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"