use serde::Deserialize;
use std::{
    collections::BTreeSet,
    env, fs,
    path::{Path, PathBuf},
};

#[derive(Debug, Deserialize)]
struct AbiManifest {
    contract_protocol_version: u16,
    limits: AbiLimits,
    contract_protocols: Vec<AbiProtocol>,
    contract_protocol_count: usize,
    client_contract_route_supported_protocol_count: usize,
}

#[derive(Debug, Deserialize)]
struct AbiLimits {
    client_max_supported_path_length: usize,
    remaining_accounts_fixed_prefix_len: usize,
}

#[derive(Debug, Deserialize)]
struct AbiProtocol {
    name: String,
    id: Option<u8>,
    contract_enum: bool,
    client_contract_route_supported: bool,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join("../contract_abi.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let manifest = read_manifest(&manifest_path);
    let generated = generate_contract_abi_module(&manifest);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("contract_abi_generated.rs"), generated)
        .expect("write generated contract ABI module");
}

fn read_manifest(path: &Path) -> AbiManifest {
    let contents = fs::read_to_string(path).expect("read contract_abi.json");
    let manifest: AbiManifest = serde_json::from_str(&contents).expect("parse contract_abi.json");

    let contract_enum_count = manifest
        .contract_protocols
        .iter()
        .filter(|protocol| protocol.contract_enum)
        .count();
    if contract_enum_count != manifest.contract_protocol_count {
        panic!(
            "contract_abi.json contract_protocol_count mismatch: declared {}, found {}",
            manifest.contract_protocol_count, contract_enum_count
        );
    }

    let client_supported_count = manifest
        .contract_protocols
        .iter()
        .filter(|protocol| protocol.client_contract_route_supported)
        .count();
    if client_supported_count != manifest.client_contract_route_supported_protocol_count {
        panic!(
            "contract_abi.json client supported protocol count mismatch: declared {}, found {}",
            manifest.client_contract_route_supported_protocol_count, client_supported_count
        );
    }

    let mut names = BTreeSet::new();
    let mut ids = BTreeSet::new();
    for protocol in &manifest.contract_protocols {
        if !names.insert(protocol.name.as_str()) {
            panic!(
                "duplicate protocol name in contract_abi.json: {}",
                protocol.name
            );
        }
        if !known_protocol_name(&protocol.name) {
            panic!("unknown protocol in contract_abi.json: {}", protocol.name);
        }
        if protocol.contract_enum && protocol.id.is_none() {
            panic!(
                "contract enum protocol has no contract id in contract_abi.json: {}",
                protocol.name
            );
        }
        if let Some(id) = protocol.id {
            if !ids.insert(id) {
                panic!("duplicate protocol id in contract_abi.json: {id}");
            }
        }
        if protocol.client_contract_route_supported && !protocol.contract_enum {
            panic!(
                "client-supported protocol is not in contract enum: {}",
                protocol.name
            );
        }
    }

    manifest
}

fn generate_contract_abi_module(manifest: &AbiManifest) -> String {
    let protocol_entries = manifest
        .contract_protocols
        .iter()
        .map(|protocol| {
            format!(
                "    ContractProtocolManifestEntry {{ name: \"{}\", id: {}, contract_enum: {}, client_contract_route_supported: {} }},\n",
                protocol.name,
                option_u8_literal(protocol.id),
                protocol.contract_enum,
                protocol.client_contract_route_supported
            )
        })
        .collect::<String>();

    format!(
        r#"// @generated by build.rs from ../contract_abi.json.
// Do not edit by hand.

pub const CONTRACT_PROTOCOL_VERSION: u16 = {contract_protocol_version};
pub const CONTRACT_PROTOCOL_COUNT: usize = {contract_protocol_count};
pub const CLIENT_MAX_SUPPORTED_PATH_LENGTH: usize = {max_path_length};
pub const REMAINING_ACCOUNTS_FIXED_PREFIX_LEN: usize = {fixed_prefix_len};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[allow(dead_code)]
pub struct ContractProtocolManifestEntry {{
    pub name: &'static str,
    pub id: Option<u8>,
    pub contract_enum: bool,
    pub client_contract_route_supported: bool,
}}

#[allow(dead_code)]
pub const CONTRACT_PROTOCOLS_MANIFEST: &[ContractProtocolManifestEntry] = &[
{protocol_entries}];
"#,
        contract_protocol_version = manifest.contract_protocol_version,
        contract_protocol_count = manifest.contract_protocol_count,
        max_path_length = manifest.limits.client_max_supported_path_length,
        fixed_prefix_len = manifest.limits.remaining_accounts_fixed_prefix_len,
        protocol_entries = protocol_entries,
    )
}

fn option_u8_literal(value: Option<u8>) -> String {
    match value {
        Some(value) => format!("Some({value})"),
        None => "None".to_string(),
    }
}

fn known_protocol_name(name: &str) -> bool {
    matches!(
        name,
        "RaydiumCPMM"
            | "RaydiumCLMM"
            | "RaydiumPoolV4"
            | "RaydiumLaunchpad"
            | "RaydiumStableSwap"
            | "PumpFunSwap"
            | "PumpFunAMM"
            | "OrcaWhirlpool"
            | "MeteoraDammV2"
            | "MeteoraDammV1"
            | "MeteoraDbc"
            | "MeteoraDlmm"
            | "ByrealCLMM"
            | "PancakeSwap"
            | "SwapIoClmm"
            | "Cube"
            | "Limo"
            | "Symmetry"
            | "RunnerRodeo"
            | "StabbleCLMM"
            | "StabbleStableSwap"
            | "StabbleWeightedSwap"
            | "GammaSwap"
            | "WoofiSwap"
            | "OrcaTokenSwapV2"
            | "Manifest"
            | "Phoenix"
            | "LifinityAmmV2"
            | "LifinityAmmV1"
            | "OrcaTokenSwapV1"
            | "SarosSwap"
            | "SplTokenSwap"
            | "DooarSwap"
            | "PenguinSwap"
            | "SenchaSwap"
            | "SaberStableSwap"
            | "MercurialStableSwap"
            | "Invariant"
            | "BonkSwap"
            | "OpenBookV2"
            | "AldrinV1"
            | "AldrinV2"
            | "SolFiV2"
            | "HumidiFi"
            | "ObricV2"
            | "Tessera"
            | "GoonFi"
            | "GoonFiV2"
            | "PerenaNumeraire"
            | "PerenaStar"
            | "MetaDaoFutarchy"
            | "Gavel"
            | "Omnipair"
            | "ScaleAmm"
            | "ScaleVmm"
            | "Virtuals"
            | "Trends"
            | "FusionAmm"
            | "Deriverse"
            | "Carrot"
            | "HyloExchange"
            | "MSwap"
            | "Guacswap"
            | "Cropper"
            | "Dexlab"
            | "LemmingsFi"
            | "Hadron"
            | "BisonFi"
            | "Voltr"
            | "OneDex"
            | "Huma"
            | "SolayerEndoAvs"
            | "HyloEarnPool"
            | "JupiterLendEarn"
            | "HeliumTreasuryManagement"
            | "SaberAddDecimals"
            | "WhaleStreet"
            | "BinaryFi"
            | "XOrca"
            | "Kipseli"
            | "Riptide"
            | "Metric"
            | "TaurusFi"
            | "Scorch"
            | "Aquifer"
            | "VaultLiquidUnstake"
            | "Wavebreak"
            | "Vertigo"
            | "MarcoPolo"
            | "MarinadeFinance"
            | "Rise"
            | "Dradex"
            | "BonfidaDexV4"
            | "GfxSsl"
            | "DumpFun"
            | "JupiterPerpetuals"
            | "TokenMillV2"
            | "YeetAmm"
            | "SegaCpmm"
            | "SugarMoney"
            | "SerumV3"
            | "SanctumInfinity"
            | "SolFiV1"
            | "FluxBeam"
            | "CremaClmm"
            | "SanctumRouter"
            | "Moonit"
            | "BoopFun"
            | "Heaven"
            | "SarosDlmm"
    )
}
