
[package]
name = "arbitrage_contract"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "arbitrage_contract"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
devnet = ["raydium-cp-swap/devnet"]
idl-build = ["anchor-lang/idl-build"]

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = "=0.30.1"
anchor-spl = "=0.30.1"

# DEX CPI dependencies  
raydium-cp-swap = { git = "https://github.com/raydium-io/raydium-cp-swap", rev = "34a208a4738b0ac070f32ac51a7c00f0982df764", features = ["no-entrypoint", "cpi"] }
pumpfun-cpi = "2.0.1"
pumpswap-sdk = "1.0.2"

# Additional dependencies matching raydium-cpi-example
solana-program = "^1.17.3"
spl-token = "=4.0.0"
spl-memo = "=4.0.0"
num_enum = "=0.7.3"
ahash = "=0.8.6"


